In [31]:

import numpy as np

# Tạo mảng
a = np.array([1,2,3])

# In mảng
print(a)

# In ra 1 phần tử
element = a[1]
print(element)

[1 2 3]
2


In [35]:
# Tạo mảng 2 chiều
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)

# In một phần tử
element = matrix[1, 2]
print(element)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [37]:
# tao mang 
# tao mang all 1
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [39]:
#tao mang 
a = np.empty(5)
print(a)

[1. 1. 1. 1. 1.]


In [41]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [45]:
#xac dinh kieu du lieu
a = np.ones(5,dtype=np.int64)
a

array([1, 1, 1, 1, 1], dtype=int64)

In [47]:
#them , xoa , sap xep
#tao mang ban dau 
arr = np.array([3,1,2,4,5])
print(arr)

[3 1 2 4 5]


In [49]:
#sap xep 
arr = np.sort(arr)
print(arr)

[1 2 3 4 5]


In [51]:
#sap xep nguoc 
arr = np.sort(arr)[::-1]
print(arr)

[5 4 3 2 1]


In [53]:
#them phan tu vao mang 
arr = np.append(arr,100)
print(arr)

[  5   4   3   2   1 100]


In [55]:
#xoa di mot vi tri nao do trong mang 
arr = np.delete(arr,3)
print(arr)

[  5   4   3   1 100]


In [59]:
#tao mang 2 chieu 
arr = np.array([[3,1,2],
              [4,6,8],
               [9,7,5]]
              )
sap_xep_theo_hang = np.sort(arr,axis=1)#tang dan
print(sap_xep_theo_hang)

[[1 2 3]
 [4 6 8]
 [5 7 9]]


In [61]:
sap_xep_theo_cot = np.sort(arr,axis=0)#tang dan
print(sap_xep_theo_cot)

[[3 1 2]
 [4 6 5]
 [9 7 8]]


In [65]:
#tao mot mang 2D
arr = np.array([[1,2,3],[4,5,6]])
#su dung cac thuoc tinh de lay thong tin ve mang 
so_chieu = arr.ndim #so chieu(2 chieu)
kich_thuoc = arr.size #kich thuoc(tong so phan tu,6)
hinh_dang = arr.shape #hinh dang (so hang x so cot ,(2,3))

print("so chieu : " ,so_chieu)
print("kich thuoc : ",kich_thuoc)
print("hinh dang : ",hinh_dang)

so chieu :  2
kich thuoc :  6
hinh dang :  (2, 3)


In [67]:
#chuyen doi kieu du lieu
arr = np.array([1,2,3,4,5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [71]:
#thay doi hinh dang cua mang 
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [73]:
reshaped_arr = reshaped_arr.flatten() #chuyen thanh mang 1 chieu
print(reshaped_arr)

[1 2 3 4 5 6]


In [75]:
#cat lat mang 
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:4] #cat tu phan tu thu 1 den 4 
print(sub_arr) 

[2 3 4]


In [77]:
sub_arr = arr[:-1] #1 2 3 4 
print(sub_arr)

[1 2 3 4]


In [85]:
sub_arr = arr[-2:]  # 4 5 
print(sub_arr)

[4 5]


In [89]:

# chuyen vi tri mang 
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [91]:
# Để chuyển vị mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [93]:

# Nối mảng
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [95]:
# II. (Sum)
# ham nmpy.sum() cho phep tinh tong cac phan tu trong mang
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Tổng của mảng arr:", total)


Tổng của mảng arr: 15


In [97]:
# III. ham tinh trung binh (Mean)
# - Hàm numpy.mean() tính giá trị trung bình của các phần tử trong mảng.
average = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average)

Giá trị trung bình của mảng arr: 3.0


In [99]:
# IV. ham tim min va max (Max và Min)
max_value = np.max(arr)
min_value = np.min(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

Giá trị lớn nhất trong mảng arr: 5
Giá trị nhỏ nhất trong mảng arr: 1
